services:
  - type: web
    name: koyl-ai-backend
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    rootDirectory: backend
